version: "3"

services:
  # web:
  #   image: apache
  #   build: ./webapp
  #   container_name: apache
  #   restart: always
  #   ports:
  #     - "8080:80"

  cypress:
    image: cypress
    build: ./course-auto-view
    container_name: cypress
    env_file:
      - ./course-auto-view/.env
    environment:
      - DISPLAY
    command:
      - /bin/sh
      - -ec
      - |
          echo "------------- START CYPRESS DEV MODE"
          npx cypress open
          # npx cypress run

    volumes:
      - ./course-auto-view/cypress:/app/cypress
      - ./course-auto-view/cypress.config.js:/app/cypress.config.js
